### ISSUE TITLE
Can't get `with: description:` to work

### ISSUE THREAD

**Issue by cgriego** [atlassian/gajira-find-issue-key#2]
I'm listening to

```yaml
on:
  pull_request_review:
    types: [submitted]
```

I'm trying to use the jsonpath functionality, but I can't get it to work. I'm not sure `argv._` works as expected.

Here's my step
```yaml
    - name: Find issue key in commit messages
      id: find
      uses: atlassian/gajira-find-issue-key@v2.0.1
      with:
        from:
        ref: '{{event.pull_request.head.ref}}'
```

I get this error.

```
##[error]TypeError: Cannot read property 'join' of undefined
5
##[error]Node run failed with exit code 1
```
