### ISSUE TITLE
TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by cicciodifranco** [atlassian/gajira-find-issue-key#24]
When I try to use this action with `pull_request`

```yml
on:
  pull_request:
    types: [closed]
    branches: [master]
```

I receive this error
```
TypeError: Cannot read property 'map' of undefined
```

**Comment by finsterdexter** [comment]
Until they add proper support for pull_request, you can workaround like so:

```
  with:
    string: ${{ github.event.pull_request.title }}
```

**Comment by brennerm** [comment]
FYI You can workaround this bug by setting an empty string for the from input:

```yaml
- uses: atlassian/gajira-find-issue-key@v2.0.2
  with:
    string: ${{ github.event.pull_request.title }}
    from: ""
```

**Comment by SudKul** [comment]
Hi All, 
I am also facing the same error:
```
Run atlassian/gajira-find-issue-key@master
  with:
    from: commits
Error: TypeError: Cannot read property 'map' of undefined
```
Is this a valid way to fetch PR object's data? I want to fetch the PR number, title, and description.

```yaml
    - name: Find in commit messages
      uses: atlassian/gajira-find-issue-key@master
      with:
        from: commits
```

```yaml
${{ github.event.pull_request.number }} 
${{ github.event.pull_request.title }}  
${{ github.event.pull_request.description }}
```
Thanks in advance.

**Comment by xakraz** [comment]
Any hope to see a fix ?
🙏🏻

**Comment by sshaw** [comment]
Having this problem when trying to get the ID from commits when PR is merged. [The variables used by this action](https://github.com/atlassian/gajira-find-issue-key/blob/25176f03aef1ee1edea04179e8d9b629c446869d/action.js#L6) are blank in this context. 

As I fix I did the following which gets the ID from the PR's branch:


```yml
- uses: atlassian/gajira-find-issue-key@v2.0.2
  id: find_jira_issue
  with:
    string: ${{ github.head_ref }}
```

You may be able to do the same with commits via `string:  ${{ github.event.commits.map(c=>c.message).join(' ') }}` but I did not test this. :octocat:
