### ISSUE TITLE
How can i solve this issue "Error: ENOENT: no such file or directory, open '/home/runner/jira/config.yml'"

### ISSUE THREAD

**Issue by atapatel** [atlassian/gajira-find-issue-key#32]
getting error
Run atlassian/gajira-find-issue-key@master
  with:
    from: commits
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/runner/jira/config.yml'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Object.104 (/home/runner/work/_actions/atlassian/gajira-find-issue-key/master/dist/index.js:1:7925)
    at __webpack_require__ (/home/runner/work/_actions/atlassian/gajira-find-issue-key/master/dist/index.js:1:154)
    at startup (/home/runner/work/_actions/atlassian/gajira-find-issue-key/master/dist/index.js:1:291)
    at module.exports.18 (/home/runner/work/_actions/atlassian/gajira-find-issue-key/master/dist/index.js:1:346)
    at Object.<anonymous> (/home/runner/work/_actions/atlassian/gajira-find-issue-key/master/dist/index.js:1:356)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/runner/jira/config.yml'

**Comment by rokcarl** [comment]
I managed to solve this by logging in. Add another step before the one you're doing:

```
            - name: Jira login
              uses: atlassian/gajira-login@v2.0.0
              env:
                  JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
                  JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
                  JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
```

It's a pretty bad error message though.
