### ISSUE TITLE
Is it planed to find multiple issues ?

### ISSUE THREAD

**Issue by guillaumewuip** [atlassian/gajira-find-issue-key#4]
Thanks for this Github Action!

Is it planed for this actions to find multiple JIRA issues key ? 

My use case : 
Some teams deploy to production by adding a tag on their default branch after having merge multiple PRs. They can link JIRA tickets in the Github Release description or a bot like https://github.com/toolmantim/release-drafter can do it for them.
It would be great for this release description to be parsed by gajira-find-issue-key and all JIRA keys found to be returned.

If this is planed or if this is something you're ok to add, how can I help ?

**Comment by tetienne** [comment]
Would be nice to have an answer.

**Comment by jamie-wearsafe** [comment]
My fork does it:
https://github.com/Broadshield/gajira-find-issue-key

**Comment by jamie-wearsafe** [comment]
As in:

```yaml
name: Pull Request - Jira Integration
on:
  pull_request:
    types:
      - synchronize
      - create
      - edit

jobs:
  jira_integration:
    runs-on: Ubuntu-18.04
    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: Atlassian Login
        uses: atlassian/gajira-login@master

      - name: Get Jira Issues
        id: jira
        continue-on-error: true
        uses: Broadshield/gajira-find-issue-key@master
        with:
          github-token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          from: pull_request
          returns: all
          include-merge-messages: true
          generate-github-milestones: true
          generate-github-issues: true
          standardize-pr-title: true
          jira-transition-on-new-branch: in progress
          jira-transition-on-pr-open: code review
          jira-transition-on-pr-approval: testing
          jira-transition-on-pr-merge: testing
          jira-transition-chain: triage,to do,solution review,in progress,code review,testing,closed
      - name: show outputs
        id: b64
        run: |
          echo "PR Title found:  ${{steps.jira.outputs.title}}"
          echo "Issues found:  ${{steps.jira.outputs.issues}}"
          releasenotes=$(printf "Release notes:  \n${{steps.jira.outputs.notes}}" | base64)
          echo "::set-output name=notes::${releasenotes}"

    outputs:
      notes: ${{steps.b64.outputs.notes}}
      issues: ${{steps.jira.outputs.issues}}
      title: ${{steps.jira.outputs.title}}
```
