### ISSUE TITLE
Get issue key from head branch?

### ISSUE THREAD

**Issue by calvinh8** [atlassian/gajira-find-issue-key#9]
I would love to transition the ticket when a PR is opened. I tried doing it like the following but had no luck.

```
name: PR

on:
  pull_request:
    branches:
      - master

jobs:
  transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest

    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: echo messages
      run: |
        echo "head ${{ github.head_ref }}"
        echo "${{ github.ref }}"

    - name: Find in commit messages
      id: find
      uses: atlassian/gajira-find-issue-key@master
      with:
        from: commits

    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.find.outputs.issue }}
        transition: "In Review"
```

i also tried with `from: branch` in the find step. however, i don't think `commit` object is available in `pull_request` event. `branch` is referring to `github.ref` which in `pull_request` event it's not referencing to the head branch but `refs/pull/:prNumber/merge`. https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request

will you be supporting finding issue key from head branch in PRs?

thanks
